### ISSUE TITLE
ModuleNotFoundError: No module named 'dsgn',   Is there a solution?

### ISSUE THREAD

**Issue by XinPeiHou** [meteorshowers/X-StereoLab#46]
(xstereolab) root@c792cba59ad3:/mnt/X-StereoLab-master# python3 tools/train_net_disp.py --cfg ./configs/config_disp.py --savemodel ./outputs/MODEL_NAME -btrain 4 -d 0-3 --multiprocessing-distributed
Traceback (most recent call last):
  File "tools/train_net_disp.py", line 25, in <module>
    from disparity.models import *
  File "/mnt/X-StereoLab-master/disparity/models/__init__.py", line 1, in <module>
    from .stereonet import StereoNet
  File "/mnt/X-StereoLab-master/disparity/models/stereonet.py", line 11, in <module>
    from dsgn.utils.bounding_box import compute_corners, quan_to_angle, \

**Comment by yHoweM** [comment]
You can download it from other stereo network.

**Comment by linglonglu** [comment]
> You can download it from other stereo network.

how to download?what is the model 'dsgn 'please

**Comment by oskar0812** [comment]
> > You can download it from other stereo network.
> 
> how to download?what is the model 'dsgn 'please

is there any solutions please?
